					<x-layouts.admin :title="'Dashboard | ToursHub'">
						<div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="mb-2 text-xs font-bold uppercase tracking-[.22em] text-[#a84e31]">Owner overview</p><h1 class="serif text-4xl sm:text-5xl">Tableau de Bord Admin</h1><p class="mt-3 max-w-xl text-sm text-[#6d776c]">Keep an eye on requests, confirmed days, and the experiences guests love most.</p></div><a href="{{ route('admin.packages.create') }}" class="rounded-xl bg-[#2e4033] px-5 py-3 text-center text-sm font-semibold text-white hover:bg-[#233329]">+ Add package</a></div>
						<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
							@foreach ([['Total orders', $totalOrders, '#e8f1f6'], ['Pending requests', $pendingOrders, '#fff4d8'], ['Confirmed bookings', $confirmedBookings, '#e0f2e9'], ['Completed tours', $completedTours, '#e4efdc'], ['Total revenue', 'MAD '.number_format($totalRevenue, 0), '#f8e5da']] as $stat)
								<div class="shadow-soft rounded-2xl border border-[#ebe8df] bg-white p-5"><span class="mb-5 grid h-10 w-10 place-items-center rounded-xl text-lg" style="background:{{ $stat[2] }}">✦</span><p class="text-xs text-[#778078]">{{ $stat[0] }}</p><p class="mt-1 text-2xl font-bold">{{ is_numeric($stat[1]) ? number_format($stat[1]) : $stat[1] }}</p></div>
							@endforeach
						</div>
						<div class="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section class="shadow-soft rounded-2xl border border-[#ebe8df] bg-white p-5 sm:p-6"><div class="mb-5 flex items-center justify-between"><div><h2 class="text-lg font-bold">Monthly revenue</h2><p class="text-xs text-[#778078]">Confirmed and completed orders</p></div><span class="rounded-lg bg-[#f3eee5] px-3 py-2 text-xs text-[#657064]">Live data</span></div><div class="h-72"><canvas id="revenue-chart"></canvas></div></section><section class="shadow-soft rounded-2xl border border-[#ebe8df] bg-white p-5 sm:p-6"><div class="mb-5"><h2 class="text-lg font-bold">Orders by month</h2><p class="text-xs text-[#778078]">Booking requests received</p></div><div class="h-72"><canvas id="orders-chart"></canvas></div></section></div>
						<div class="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section class="shadow-soft overflow-hidden rounded-2xl border border-[#ebe8df] bg-white"><div class="flex items-center justify-between border-b border-[#eeeae1] p-5 sm:p-6"><div><h2 class="text-lg font-bold">Recent orders</h2><p class="text-xs text-[#778078]">The latest customer requests</p></div><a href="{{ route('admin.orders.index') }}" class="text-sm font-semibold text-[#a84e31]">View all</a></div><div class="overflow-x-auto"><table class="w-full min-w-[620px] text-left text-sm"><thead class="bg-[#f7f4ed] text-xs uppercase tracking-wide text-[#788174]"><tr><th class="px-5 py-3">Customer</th><th class="px-5 py-3">Package</th><th class="px-5 py-3">Visit date</th><th class="px-5 py-3">Status</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-[#f0eee7]">@forelse ($recentOrders as $order)<tr><td class="px-5 py-4 font-semibold">{{ $order->customer_name }}</td><td class="px-5 py-4 text-[#687468]">{{ $order->package->title }}</td><td class="px-5 py-4 text-[#687468]">{{ $order->visit_date->format('d/m/Y') }}</td><td class="px-5 py-4"><span class="status status-{{ $order->status }}">{{ $order->status }}</span></td><td class="px-5 py-4 text-right"><a class="font-semibold text-[#a84e31]" href="{{ route('admin.orders.show', $order) }}">Details</a></td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-sm text-[#778078]">No orders yet.</td></tr>@endforelse</tbody></table></div></section><section class="shadow-soft rounded-2xl border border-[#ebe8df] bg-white p-5 sm:p-6"><h2 class="text-lg font-bold">Popular packages</h2><p class="mb-5 text-xs text-[#778078]">Most requested experiences</p><div class="space-y-4">@forelse ($packagePopularity as $package)<div><div class="mb-1 flex justify-between gap-3 text-sm"><span class="truncate font-semibold">{{ $package->title }}</span><span class="text-[#778078]">{{ $package->orders_count }}</span></div><div class="h-2 overflow-hidden rounded-full bg-[#edf0e9]"><div class="h-full rounded-full bg-[#a84e31]" style="width:{{ max(8, min(100, ($package->orders_count / max(1, $packagePopularity->first()->orders_count)) * 100)) }}%"></div></div></div>@empty<p class="text-sm text-[#778078]">Popularity will appear after bookings arrive.</p>@endforelse</div></section></div>
						<script>
							const labels = @json($revenueLabels);
							new Chart(document.getElementById('revenue-chart'), {type:'bar', data:{labels, datasets:[{label:'Revenue (MAD)', data:@json($revenueData), backgroundColor:'#a84e31', borderRadius:6}]}, options:{responsive:true, maintainAspectRatio:false, plugins:{legend:{display:false}}, scales:{y:{beginAtZero:true, grid:{color:'#eeeae1'}}, x:{grid:{display:false}}}}});
							new Chart(document.getElementById('orders-chart'), {type:'line', data:{labels:@json($orderLabels), datasets:[{label:'Orders', data:@json($orderCounts), borderColor:'#2e4033', backgroundColor:'#e0eee4', fill:true, tension:.35}]}, options:{responsive:true, maintainAspectRatio:false, plugins:{legend:{display:false}}, scales:{y:{beginAtZero:true, grid:{color:'#eeeae1'}}, x:{grid:{display:false}}}}});
						</script>
					</x-layouts.admin>
                     