@csrf
<div class="grid gap-5 sm:grid-cols-2">
    <div class="sm:col-span-2"><label class="mb-2 block text-sm font-semibold" for="title">Title</label><input class="w-full rounded-xl border border-[#deded5] px-4 py-3" id="title" name="title" value="{{ old('title', $package->title ?? '') }}" required>@error('title')<p class="mt-1 text-xs text-red-700">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label class="mb-2 block text-sm font-semibold" for="description">Description</label><textarea class="w-full rounded-xl border border-[#deded5] px-4 py-3" id="description" name="description" rows="5" required>{{ old('description', $package->description ?? '') }}</textarea>@error('description')<p class="mt-1 text-xs text-red-700">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label class="mb-2 block text-sm font-semibold" for="image">Image URL</label><input class="w-full rounded-xl border border-[#deded5] px-4 py-3" id="image" name="image" type="url" value="{{ old('image', $package->image ?? '') }}" placeholder="https://..."></div>
    <div><label class="mb-2 block text-sm font-semibold" for="price">Price (MAD / guest)</label><input class="w-full rounded-xl border border-[#deded5] px-4 py-3" id="price" name="price" type="number" min="0" step="0.01" value="{{ old('price', $package->price ?? '') }}" required></div>
    <div><label class="mb-2 block text-sm font-semibold" for="duration">Duration</label><input class="w-full rounded-xl border border-[#deded5] px-4 py-3" id="duration" name="duration" value="{{ old('duration', $package->duration ?? '') }}" placeholder="e.g. 3 hours" required></div>
    <div><label class="mb-2 block text-sm font-semibold" for="location">Location</label><input class="w-full rounded-xl border border-[#deded5] px-4 py-3" id="location" name="location" value="{{ old('location', $package->location ?? 'Agafay, Morocco') }}" required></div>
    <div><label class="mb-2 block text-sm font-semibold" for="category">Category</label><select class="w-full rounded-xl border border-[#deded5] px-4 py-3" id="category" name="category">@foreach (['adventure','food','relax','private'] as $category)<option value="{{ $category }}" @selected(old('category', $package->category ?? 'adventure') === $category)>{{ ucfirst($category) }}</option>@endforeach</select></div>
    <div><label class="mb-2 block text-sm font-semibold" for="max_guests">Maximum guests</label><input class="w-full rounded-xl border border-[#deded5] px-4 py-3" id="max_guests" name="max_guests" type="number" min="1" value="{{ old('max_guests', $package->max_guests ?? 12) }}" required></div>
    <label class="flex items-center gap-3 text-sm font-semibold sm:col-span-2"><input class="h-4 w-4" name="status" type="checkbox" value="1" @checked(old('status', $package->status ?? true))> Show this package on the landing page</label>
</div>
<div class="mt-7 flex justify-end gap-3"><a href="{{ route('admin.packages.index') }}" class="rounded-xl border border-[#dcded5] px-5 py-3 text-sm font-semibold">Cancel</a><button class="rounded-xl bg-[#2e4033] px-5 py-3 text-sm font-semibold text-white">{{ $submitLabel }}</button></div>
